### ISSUE TITLE
Make binder work with external library dependencies

### ISSUE THREAD

**Issue by Dwoosh** [Tetrite/cBinder#5]

**Comment by Dwoosh** [comment]
check 'libraries' optional argument in set_source. I think it links dll libraries

**Comment by Dwoosh** [comment]
Cffi calls distutils/setuptools to build extension so every keyword arg in set_sources is passed on. Use include_dirs, libraries, library_dirs args to work with external libraries. See here: https://docs.python.org/3/extending/building.html

**Comment by Dwoosh** [comment]
Small test worked: include_dirs=['C:\\MinGW\\include'] hardcoded path to gsl library worked but failed on some internal dependency: https://pastebin.com/vcEdQREb

**Comment by Sopel97** [comment]
problem jest taki ze jesli msvc jest zainstalowane to cffi domyslnie go uzywa zamiast gcc

a headery mingw pewnie maja sporo niekompatybilnych skladniowo headearów.

W dodatku msvc jako tako nie ma bezpośredniego wsparcia dla C, więc nie zdziwiłbym się gdyby były dalsze problemy.

**Comment by Dwoosh** [comment]
Wiem, dlatego zleciłem @youPickItUp przetestowanie tego pod linuxem
